#!/usr/bin/env bash
# Install nginx web server

# Step 1 – Installing Nginx
apt update
apt install nginx -y

# Nginx listening on port 80

sed -i 's/listen [::]:80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# querying Nginx at its root / with a GET request (requesting a page) using curl

cat <<EOF > /var/www/html/index.html
Hello World!
EOF

# Restart nginx
service nginx restart
